spring.application.name=BatoiLogic API

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=4206
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=5000

# JWT
jwt.secret=hgagr513º1lkaur*?karu>>126#@!$%&/()=+
jwt.expiration=3240000

# Nominatim
nominatim.url=https://nominatim.openstreetmap.org/search


# Logging
logging.level.com.batoilogic=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true

# Errores
server.error.include-message=always
server.error.include-exception=true